version: "2"
run:
  issues-exit-code: 1
  build-tags:
    - nosound
linters:
  default: none
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
issues:
  max-issues-per-linter: 0
  max-same-issues: 0