version: "2"
run:
  issues-exit-code: 1
  allow-parallel-runners: true
  build-tags:
    - nosound
  skip-dirs:
    - vendor
    - third_party
linters:
  default: none
  enable:
    - bodyclose
    - decorder
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - exhaustive
    - gocheckcompilerdirectives
    - gochecksumtype
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - mirror
    - misspell
    - mnd
    - nakedret
    - nilnil
    - nolintlint
    - perfsprint
    - prealloc
    - predeclared
    - revive
    - sloglint
    - staticcheck
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl_v5
settings:
  decorder:
    disable-dec-num-check: true
    disable-dec-order-check: false
  errcheck:
    check-type-assertions: true
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
  govet:
    enable:
      - fieldalignment
  mnd:
    checks:
      - argument
      - case
      - condition
      - return
  nolintlint:
    require-explanation: true
    require-specific: true
  revive:
    rules:
      - name: error-naming
        severity: warning
        disabled: true
  wsl_v5:
    allow-first-in-block: true
    allow-whole-block: false
    branch-max-lines: 2
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: true
  exclude-rules:
    - linters:
        - dupl
        - gocyclo
        - gosec
      path: _test\.go
    - linters:
        - staticcheck
      text: error strings should not be capitalized