version: 2

project_name: focus

before:
  hooks:
    - go mod download

builds:
  - id: windows
    env:
      - CGO_ENABLED=1
    goos:
      - windows
    goarch:
      - amd64
      - arm64
    main: ./cmd/focus

  - id: linux
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/focus

archives:
  - id: windows-only
    builds:
      - windows
    files:
      - LICENCE
      - README.md
      - CHANGELOG.md
    format: zip

  - id: default
    builds:
      - windows
      - linux
    files:
      - LICENCE
      - README.md
      - CHANGELOG.md
    format: tar.gz

checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: 'master'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

nfpms:
  - id: main_packages
    vendor: '{{ .Env.REPO_OWNER }}'
    homepage: '{{ .Env.REPO_WEBSITE }}'
    maintainer: '{{ .Env.REPO_MAINTAINER }}'
    description: '{{ .Env.REPO_DESCRIPTION }}'
    license: MIT
    formats:
      - deb
      - rpm

    overrides:
      deb:
        dependencies:
          - libasound2-dev

      rpm:
        dependencies:
          - alsa-lib-devel

  - id: other_packages
    vendor: '{{ .Env.REPO_OWNER }}'
    homepage: '{{ .Env.REPO_WEBSITE }}'
    maintainer: '{{ .Env.REPO_MAINTAINER }}'
    description: '{{ .Env.REPO_DESCRIPTION }}'
    license: MIT
    formats:
      - apk
      - termux.deb
      - archlinux

    dependencies:
      - libasound2-dev

    overrides:
      archlinux:
        dependencies:
          - alsa-lib

publishers:
  - name: fury.io
    ids:
      - main_packages
    dir: '{{ dir .ArtifactPath }}'
    cmd: curl -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_PUSH_TOKEN }}@push.fury.io/{{ .Env.FURY_USERNAME }}/

