name: Lint code
on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go ${{ vars.GO_VERSION }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ vars.GO_VERSION }}

      - name: Install libasound2-dev
        run: sudo apt install -y libasound2-dev

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest
